### ISSUE TITLE
Safari crashing after closing safari

### ISSUE THREAD

**Issue by Ferbee** [p2kdev/SafariFastType#2]
[text 2.txt](https://github.com/p2kdev/SafariFastType/files/6530579/text.2.txt)

crash log

**Comment by p2kdev** [comment]
@Ferbee -> I can't seem to reproduce the crash. Can you provide the steps to reproduce this issue? Also does it happen every time?

**Comment by Ferbee** [comment]
Open safari, new tab, (keyboard comes up), go home, open app switcher, kill safari, and crash message appears

It happens every time

**Comment by p2kdev** [comment]
Just tried and not getting any crashes whatsoever. Perhaps you have some other tweak conflict.
